name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 1 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ecd95d0532dbe067262721459ef4a4b5
          TIMEZONE: Asia/Seoul
 
